### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by uceka** [UnaPibaGeek/ctfr#21]
I got an error. Please check the following outputs;

python3 ctfr.py -d starbucks.com

          ____ _____ _____ ____
         / ___|_   _|  ___|  _ \
        | |     | | | |_  | |_) |
        | |___  | | |  _| |  _ <
         \____| |_| |_|   |_| \_\

     Version 1.2 - Hey don't miss AXFR!
    Made by Sheila A. Berta (UnaPibaGeek)

Traceback (most recent call last):
  File "ctfr.py", line 80, in <module>
    main()
  File "ctfr.py", line 65, in main
    subdomains.append(value['name_value'])
TypeError: list indices must be integers or slices, not str

**Comment by UnaPibaGeek** [comment]
Fixed by @becksteadn. I merged the PR to master. Thanks.

**Comment by maravento** [comment]
When do you fix this error? I just cloned the repository and the same error still comes up. Thk
![Captura de pantalla -2019-10-10 16-36-35](https://user-images.githubusercontent.com/14880802/66608442-2de58780-eb7c-11e9-9b64-abbb31d2bbd5.png)
